### ISSUE TITLE
Slow writes into influx

### ISSUE THREAD

**Issue by Korkd** [fangli/fluent-plugin-influxdb#11]
I've been trying to troubleshoot an issue where writes into influx seem to come in very slowly over time. My setup is as follows:

influxdb 0.8.8
fluent-plugin-influxdb (0.1.4)
fluentd (0.12.8)

fluentd config:
<match fuse.**>
  type influxdb
  host  ***
  port  8086
  dbname ***
  user  ***
  password  ***
  time_precision ms
  buffer_type memory
  buffer_chunk_limit 524288 # 512 * 1024
  buffer_queue_limit 1024
  flush_interval 30
  retry_limit 17
  retry_wait 1.0
</match>

I've played around and tried a number of different combinations of the config.

I have 2 fluentd instances dumping into a single influxdb instance. All machines are barely registering any CPU usage when messages are being sent, but it takes 20-30 minutes for the buffers to clear out into influx after all the data has been written to fluentd. This is around 72000 messages total (each message is ~100 bytes) being sent.

Turning debug logging on in influx I see a ton of spam about authenticating the user specified in the fluentd config, 10-20 a second. Any thoughts on what the issue might be?

**Comment by repeatedly** [comment]
Hmm...

https://github.com/fangli/fluent-plugin-influxdb/blob/92eb4ac15e48a4df15043722a632ac8b7dd7c3c9/lib/fluent/plugin/out_influxdb.rb#L49

Currently, we use `write_ponit` for each record.
It may causes slowly insertion. I will check the performance with array version.

**Comment by repeatedly** [comment]
Sorry for the delay.
Could you try this PR code? > https://github.com/fangli/fluent-plugin-influxdb/pull/12

**Comment by repeatedly** [comment]
@Korkd ping? If you okay, I will merge PR and release new version.

**Comment by Korkd** [comment]
Sorry to take so long to get back to you, haven't had a chance to look into this again until today. Good news though, it appears to have solved the problem. I'm no longer getting long delays between results!

**Comment by repeatedly** [comment]
Good :)
