### ISSUE TITLE
influxdb 0.9 compatibility?

### ISSUE THREAD

**Issue by chrishiestand** [fangli/fluent-plugin-influxdb#15]
It looks like this plugin isn't 0.9 compatible. I'm trying to use it against influxdb 0.9 and getting:

   2015-06-04 15:07:04 -0700 [warn]: fluent/output.rb:354:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2015-06-04 15:07:05 -0700 error_class="InfluxDB::Error" error="404 page not found\n" plugin_id="object:3fd80a06ce04"

This looks a lot like this: https://github.com/influxdb/influxdb/issues/2032

Assuming the problem is indeed 0.9 compatibility, it would be great to have a 0.9 compatible branch of this repository.

**Comment by repeatedly** [comment]
We use official influxdb gem. Supporting 0.9 in influxdb gem is enough.
This plugin doesn't lock gem version so you can use any version of influxdb gem.

**Comment by repeatedly** [comment]
I check influxdb-ruby repository and I don't know why influxdb team doesn't release new gem...

**Comment by chrishiestand** [comment]
Yes, thank you for looking into this. I'm not quite sure how ruby package management works, but if you could create a 0.9 branch of fluent-plugin-influxdb when the 0.9 influxdb gem is released that would be great. (Or use master and move fluent-plugin-influxdb 0.8 to a separate branch).

**Comment by repeatedly** [comment]
It depends on influxdb gem for 0.9.
If influxdb gem for 0.9 changed its client API, I will consider it.

**Comment by jorrizza** [comment]
I have the same issue. I think it's influxdb/influxdb-ruby#91 that's the source of this issue. The entire gem just does not support the latest version of influxdb yet.

The 0.8 API is still used, see for instance [client.rb](https://github.com/influxdb/influxdb-ruby/blob/master/lib/influxdb/client.rb#L111).

**Comment by williampratt** [comment]
When pull request #23 is added, support for 0.9 will work. Influxdb-ruby 0.2.0 has been released so any new installs of this gem will break since the version isn't locked and 0.2.0 doesn't support Influx 0.8.
