### ISSUE TITLE
Gracefully Upgrading to InfluxDB 0.9 Support

### ISSUE THREAD

**Issue by jonmchan** [fangli/fluent-plugin-influxdb#20]
The influxdb-ruby library is moving to 0.9 support. Influxdb-ruby v0.1.9 will be the last version that supports 0.8. Without a version constraint on fluent-plugin-influxdb for influxdb-ruby, many new production deployments that have not upgraded to 0.9 will fail un-expectantly.

I recommend that we add a constraint to use only influxdb-ruby v0.1.9 so that we will not fail to work with 0.8 when the next version is released. It might be useful to start versioning fluent-plugin-influxdb such that version 0.1.* works with influxdb 0.8 while a fluent-plugin-influxdb 0.2.* version is compatible with influxdb 0.9. If people use Semver correctly, this should help so that we don't get any surprises in production.

**Comment by repeatedly** [comment]
I will do it tomorrow.

**Comment by repeatedly** [comment]
Fixed by https://github.com/fangli/fluent-plugin-influxdb/pull/21

**Comment by jonmchan** [comment]
PR #21 looks good. Thanks for adding this!

**Comment by jonmchan** [comment]
@repeatedly Influxdb-ruby 0.2.0 just got released and it broke our system. :( I think that PR #21 has a bug. I think you mean ~<0.1.8 and not ~>0.1.8 in https://github.com/fangli/fluent-plugin-influxdb/blob/master/fluent-plugin-influxdb.gemspec#L20. When we redeployed fluentd, we ended up with influxdb-ruby 0.2.0.
