### ISSUE TITLE
gemspec for 0.1.8 causes issues

### ISSUE THREAD

**Issue by williampratt** [fangli/fluent-plugin-influxdb#25]
The gemspec for 0.1.8 specifies the dependency of influxdb as ~>0.1.8 which causes it to install 0.2.0 which is not compatible with Influx 0.8. I believe it should be changed to either just 0.1.8 or ~<0.1.8.

**Comment by repeatedly** [comment]
> The gemspec for 0.1.8 specifies the dependency of influxdb as ~>0.1.8 which causes it to install 0.2.0 which is not compatible with Influx 0.8.

No. `~> 0.1.8` doesn't install 0.2.0.

**Comment by williampratt** [comment]
Strange, it is for us. We had to manually install 0.1.8 first to prevent it.
