### ISSUE TITLE
Plugin prevents fluentd from shutting down when database is not online.

### ISSUE THREAD

**Issue by tsailiming** [fangli/fluent-plugin-influxdb#29]
I had to make the following change, otherwise the thread will forever attempt to connect to the database. when it is not online. 

````
def shutdown
    @influxdb.stop!
end
````

**Comment by repeatedly** [comment]
I commented on ML.
This behaviour is not good for users.
We should warn message like "influxdb has already shutted down. If you use a plugin with memory buffer, logs may lost".
Could you send a PR?

**Comment by Jimilian** [comment]
@tsailiming Any updates? I would be very happy to see any logs in this case from plugin :)

**Comment by tsailiming** [comment]
Sorry, I dont have the logs. No longer using fluentd at the moment.

**Comment by repeatedly** [comment]
https://github.com/fangli/fluent-plugin-influxdb/pull/49 includes this patch for more safety shutdown.
