### ISSUE TITLE
one second has only one data

### ISSUE THREAD

**Issue by timopek** [fangli/fluent-plugin-influxdb#34]
My timestamp is 2015-12-13T07:39:31Z, but when  insert to influxdb has only one message in one second. In fact, one second has more than one message. 

fluent-plugin-influxdb (0.2.2)
influxdb (0.2.3)
influxdb server : 0.9.6.1

By the way: the config "tag_keys"  isn't efficient.

**Comment by timopek** [comment]
I set only one tag_keys, so influxdb has only one data in one second.

**Comment by hiepsikhokhao** [comment]
Hi @timopek ,

Influxdb is time series database like Nosql

Key: Time + tags
Value: Fields

So, if at the same time and same tags value , fileds will be overwritten. That's why you see only a point in a second.

Regards
