### ISSUE TITLE
Database presence check is not work with non-admin user

### ISSUE THREAD

**Issue by atfujiwara** [fangli/fluent-plugin-influxdb#47]
I got an error message like following after I upgrade this plugin to v2.5:

`2016-04-22 15:25:57 +0900 [error]: unexpected error error_class=InfluxDB::AuthenticationError error=#<InfluxDB::AuthenticationError: {"error":"error authorizing query: (username) not authorized to execute statement 'SHOW DATABASES', requires admin privilege"}>`

I confirmed if I add admin privilege to that user, this error is not shown and the data is imported to InfluxDB correctly. But in my opinion, it's too much for data collection process.

**Comment by repeatedly** [comment]
Ah, I see. How about skip this check when InfluxDB::AuthenticationError happens like below?

```rb
begin
  # database check
rescue InfluxDB::AuthenticationError 
  log.info "skip database check bacuse specified user doesn't have amin privilege"
end
```

**Comment by repeatedly** [comment]
#48 for this problem.

**Comment by atfujiwara** [comment]
Thank you for your quick response!

**Comment by repeatedly** [comment]
Release v0.2.6.
