### ISSUE TITLE
Problem with plugin updating influxdb

### ISSUE THREAD

**Issue by clarencehj** [fangli/fluent-plugin-influxdb#5]
Im seeing the following error when trying to send dstat data through fleuntd to influxdb using this plugin.

Versions:
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-dstat-0.2.5
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-influxdb-0.1.2
influxDB  ( Tested version 0.6.0 & 0.8.2 )

The error is :

2014-09-14 16:17:28 -0400 [warn]: fluent/output.rb:344:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2014-09-14 16:17:28 -0400 error_class="Net::HTTPServerException" error="400 \"Bad Request\"" instance=-608640758
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-influxdb-0.1.2/lib/fluent/plugin/out_influxdb.rb:50:in `write'
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.53/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.53/lib/fluent/buffer.rb:276:in `pop'
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.53/lib/fluent/output.rb:311:in `try_flush'
  2014-09-14 16:17:28 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.53/lib/fluent/output.rb:132:in `run'

----

My system configuration file for fluentd
<source>
  type dstat
  tag input.dstat
  option -c
  delay 5
 </source>   

  #option -cdmsy
<match input.dstat>
  type influxdb
  host  192.168.1.6 
  port  8086
  dbname dstat
  user  xxxx
  password  xxxx
  time_precision s
</match>

------

Wireshark packet trace
Wireshare Packet Trace:

POST /db/dstat/series?u=xxxx&p=xxxx&time_precision=s HTTP/1.1
Content-Type: application/json; charset=utf-8
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Accept: */*
User-Agent: Ruby
Connection: close
Host: 192.168.1.6:8086
Content-Length: 2571

[{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"1.148","sys":"0.863","idl":"97.556","wai":"0.135","hiq":"0.049","siq":"0.249"}},1410673009]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"3.441","sys":"0.810","idl":"95.749","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673009]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.202","sys":"0.202","idl":"99.194","wai":"0.0","hiq":"0.0","siq":"0.403"}},1410673014]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.202","idl":"99.798","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673019]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.202","sys":"0.0","idl":"99.798","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673024]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.202","idl":"99.597","wai":"0.0","hiq":"0.202","siq":"0.0"}},1410673029]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.0","idl":"100.0","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673034]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.203","idl":"99.797","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673039]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.202","idl":"99.798","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673044]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.0","idl":"100.0","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673049]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.0","idl":"100.0","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673054]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.201","sys":"0.201","idl":"99.598","wai":"0.0","hiq":"0.0","siq":"0.0"}},1410673059]]},{"name":"input.dstat","columns":["hostname","dstat","time"],"points":[["new-host-3",{"total cpu usage":{"usr":"0.0","sys":"0.0","idl":"99.798","wai":"0.0","hiq":"0.202","siq":"0.0"}},1410673064]]}]

====>
HTTP/1.1 400 Bad Request
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 2592000
Content-Type: text/plain
Date: Sun, 14 Sep 2014 05:37:45 GMT
Content-Length: 36
Connection: close

Unknown type map[string]interface {}

====

**Comment by repeatedly** [comment]
Sorry for the delay reply.
Latest version v0.1.3 now use influxdb official client.
Does using v0.1.3 still have this problem?

**Comment by repeatedly** [comment]
No response.
Maybe latest version fix this problem.
