### ISSUE TITLE
InfluxDB empty field if tag is used

### ISSUE THREAD

**Issue by ton31337** [fangli/fluent-plugin-influxdb#56]
Hi,

if I use `tag_keys ["vhost_Uid"]`, series are created like `something.metrics,vhost_Uid=123`, but selecting from `something.metrics`, that `vhost_Uid` field is `null`. Is it really need to be skipped in `values`?

https://github.com/fangli/fluent-plugin-influxdb/blob/master/lib/fluent/plugin/out_influxdb.rb#L117-L122

Donatas.

**Comment by repeatedly** [comment]
You mean `vhost_Uid` values of `SELECT * FROM measurement_name` are always `null`?

**Comment by ton31337** [comment]
Everything is ok
