### ISSUE TITLE
in rc2 version error: fluent-logger for nodejs (set milliseconds:1):report error:error="undefined method `nsec' for 1488276994397.0:Float\nDid you mean?  inspect

### ISSUE THREAD

**Issue by linxuanwei** [fangli/fluent-plugin-influxdb#71]
I use fluent-logger nodejs.
var config = {
    host: 'localhost',
    port: 24224,
    timeout: 3.0,
    milliseconds: 1
};

when I write log to influxdb through fluent(support milliseconds?  support nodejs?)

error came:

2017-02-28 10:16:37 +0000 [error]: #0 unexpected error on reading data host="172.17.0.1" port=33606 error_class=NoMethodError error="undefined method `nsec' for 1488276994397.0:Float\nDid you mean?  inspect"

  2017-02-28 10:16:37 +0000 [error]: #0 suppressed same stacktrace
49131-08-17 16:48:06.000000000 +0000 test: {"level":"info","message":"newdada:"}

2017-02-28 10:18:49 +0000 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `nsec' for 1488277126086.0:Float\nDid you mean?  inspect" tag="test"

**Comment by linxuanwei** [comment]
when i use:
var config = {
host: 'localhost',
port: 24224,
timeout: 3.0};


I works and no error .

**Comment by linxuanwei** [comment]
@repeatedly 

![qq20170228-183727 2x](https://cloud.githubusercontent.com/assets/10094722/23402114/3452b1d8-fde5-11e6-8721-101c46e28566.jpg)

**Comment by linxuanwei** [comment]
@repeatedly 
![qq20170228-184014 2x](https://cloud.githubusercontent.com/assets/10094722/23402171/64e9bdbe-fde5-11e6-96ae-dd6392e5f39d.jpg)


`var winston = require('winston');
var config = {
    //host: '10.9.20.79',
    host: 'localhost',
    port: 24224,
    timeout: 3.0,
    milliseconds: 1
};
var tag = 'test';
var fluentTransport = require('fluent-logger').support.winstonTransport();
var logger = new (winston.Logger)({
    transports: [new fluentTransport(tag, config), new (winston.transports.Console)()]
});

logger.log('info', 'some_data');`

**Comment by repeatedly** [comment]
fluentd doesn't support float type time unit.
fluentd accepts only Integer second precision time or EventTime nano precision time.

**Comment by linxuanwei** [comment]
I do nothing ,just use fluent-logger to send a log.

In fluent-logger source codes:
      **`  if (typeof time !== "number") {
          time = Math.floor((time ? time.getTime() : Date.now()) / this._timeResolution);
       }

     var packet = [tag, time, data];**`


fluent-logger use Integer not Float type.
why is Float error? where auto convert Integer type to Float in source codes?

**Comment by linxuanwei** [comment]
`var winston = require('winston');
var config = {
    //host: '10.9.20.79',
    host: 'localhost',
    port: 24224,
    timeout: 3.0,
    milliseconds: 1
};
var tag = 'test';
var fluentTransport = require('fluent-logger').support.winstonTransport();
var logger = new (winston.Logger)({
    transports: [new fluentTransport(tag, config), new (winston.transports.Console)()]
});

logger.log('info', 'some_data');`


there are  all my test codes .
fluend write  'some_data' to influxdb.
but report Float Type Error.

I really do nothing....
@repeatedly

**Comment by linxuanwei** [comment]
If I remove 'milliseconds' option, all is ok.
@repeatedly

**Comment by linxuanwei** [comment]
I use fluentd v0.14 and fluent-plugin-influxdb v 1.0.0.rc2

**Comment by linxuanwei** [comment]
![qq20170301-124454 2x](https://cloud.githubusercontent.com/assets/10094722/23446297/fd0e8d26-fe7c-11e6-9236-65ab4a163328.jpg)
the 'time_precision' option does not  work.

**Comment by linxuanwei** [comment]
@repeatedly 

I fixed the bug  in fluent-plugin-influxdb-1.0.0.rc2/lib/fluent/plugin/out_influxdb.rb

make "fluent-plugin-influxdb"  support float

`def precision_time(time)
    # nsec is supported from v0.14
    if time.is_a?Float
        nstime = (time * (10 ** 9)).to_i
    else
        nstime = time * (10 ** 9) + (time.is_a?(Integer) ? 0 : time.nsec)
    end
    @time_precise.call(nstime)
  end`
