### ISSUE TITLE
About default_retention_policy and retention_policy_key

### ISSUE THREAD

**Issue by xingyunhui** [fangli/fluent-plugin-influxdb#78]
I don't know hot to write a "defalut_retention_policy" or "About default_retention_policy and ".
Can U give an example,
such as keep date for 30 daya ,  how can I write for "defalut_retention_policy"

**Comment by repeatedly** [comment]
"defalut_retention_policy" specify retention policy name in influxdb.

> Can U give an example,
> such as keep date for 30 daya , how can I write for "defalut_retention_policy"

Reading influxdb document is better.
