### ISSUE TITLE
Ruby Version Problem

### ISSUE THREAD

**Issue by buarmin** [fangli/fluent-plugin-influxdb#79]
Dear Friends 
    I want to use your plugin but I get  error.  
   ERROR:  Error installing fluent-plugin-influxdb:
	influxdb requires Ruby version >= 2.2.0.

  I uninstalled my ruby and installed different versions from 2.0.0, 2.2.0, 2.3, 2.4 
but the error still exist. would you please help me how to solve this. 
Thank you.

**Comment by repeatedly** [comment]
I assume you use td-agent: https://docs.fluentd.org/v0.12/articles/faq#i-installed-td-agent-and-want-to-add-custom-plugins-how-do-i-do-it

**Comment by buarmin** [comment]
Thank you for reply but it does not help 
root@c982d9f04bf6:/var/log/td-agent# /usr/sbin/td-agent-gem install fluent-plugin-influxdb
WARN: Unresolved specs during Gem::Specification.reset:
      msgpack (< 2, >= 0.5.11)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Fetching: influxdb-0.4.0.gem (100%)
ERROR:  Error installing fluent-plugin-influxdb:
	influxdb requires Ruby version >= 2.2.0.

root@c982d9f04bf6:/var/log/td-agent# ruby -v 
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by repeatedly** [comment]
> And need to use v0.3.x in ruby 2.1: https://github.com/influxdata/influxdb-ruby/blob/master/CHANGELOG.md

Please read this sentence.

**Comment by buarmin** [comment]
sorry my bad but i didn't get your clue ?

**Comment by repeatedly** [comment]
I release new version to avoid v0.4 installation.
Latest version should fix this problem.

**Comment by buarmin** [comment]
Thank you very much "Masahiro"  . I appreciate .
