### ISSUE TITLE
backslash escaping issue

### ISSUE THREAD

**Issue by CheyiLin** [fangli/fluent-plugin-influxdb#80]
Hi,

I found that the backslash escaping in the tag/field values was not working correctly as expected.

With config:
```
<match mytag>
  @type copy
  <store>
    @type stdout
  </store>
  <store>
    @type influxdb
    host influxdb
    port 8086
    dbname mydb
    tag_keys ["hostname", "v.device_name", "v.mount_point"]
  </store>
</match>
```

And input record (from metricbeat):
```
{"hostname":"my-machine","v.device_name":"D:\\","v.mount_point":"D:\\","v.total":26840395776,"v.free":5271150592,"v.available":5271150592,"v.files":0,"v.free_files":0,"v.used.pct":0.8036,"v.used.bytes":21569245184}
```

Will cause the following exception:
```
#0 taking back chunk for errors. chunk="55a01ef2e4d034e413d394ffd26be22c"
#0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-09-25 11:34:03 +0000 chunk="55a01ef2e4d034e413d394ffd26be22c" error_class=InfluxDB::Error error="{\"error\":\"unable to parse 'system.filesystem,hostname=my-machine,v.device_name=D:\\\\,v.mount_point=D:\\\\ v.total=26840395776i,v.free=5271150592i,v.available=5271150592i,v.files=0i,v.free_files=0i,v.used.pct=0.8036,v.used.bytes=21569245184i 1501729298688': invalid tag format\"}\n"
#0 /var/lib/gems/2.3.0/gems/influxdb-0.3.16/lib/influxdb/client/http.rb:85:in `resolve_error'
#0 /var/lib/gems/2.3.0/gems/influxdb-0.3.16/lib/influxdb/client/http.rb:35:in `block in post'
#0 /var/lib/gems/2.3.0/gems/influxdb-0.3.16/lib/influxdb/client/http.rb:53:in `connect_with_retry'
#0 /var/lib/gems/2.3.0/gems/influxdb-0.3.16/lib/influxdb/client/http.rb:26:in `post'
#0 /var/lib/gems/2.3.0/gems/influxdb-0.3.16/lib/influxdb/query/core.rb:78:in `write'
#0 /var/lib/gems/2.3.0/gems/influxdb-0.3.16/lib/influxdb/query/core.rb:57:in `write_points'
#0 /fluentd/plugins/out_influxdb2.rb:189:in `write'
#0 /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:1061:in `try_flush'
#0 /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:1286:in `flush_thread_run'
#0 /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin/output.rb:438:in `block (2 levels) in start'
#0 /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

The exception message shows that the record has been wrongly escaped:
(double escaped backslashes and a comma `,` before `v.total` disappeared)
```
v.device_name=D:\\\\,v.mount_point=D:\\\\ v.total=26840395776i,v.free=5271150592i,v.available=5271150592i
```

I also checked the plugin code and printed the hash `point` before calling `@influxdb.write_points()`:
```
{:timestamp=>1501729298688, :series=>"system.filesystem", :values=>{"v.total"=>26840395776, "v.free"=>5271150592, "v.available"=>5271150592, "v.files"=>0, "v.free_files"=>0, "v.used.pct"=>0.8036, "v.used.bytes"=>21569245184}, :tags=>{"hostname"=>"my-machine", "v.device_name"=>"D:\\", "v.mount_point"=>"D:\\"}}
```

I guess that it is caused by `influxdb-ruby`, but I think that asking here is a good start.
Thanks.

Environment:
```
fluentd 0.14.21
fluent-plugin-influxdb 1.0.0.rc3
influxdb-ruby 0.3.16
```

**Comment by CheyiLin** [comment]
Additional info:

If I don't tag `v.device_name` and `v.mount_point` 2 string keys, the `@influxdb.write_points()` call will work, but the data written to influxdb are wrong:
```
> SELECT "v.device_name", "v.mount_point" FROM "mydb"."system.filesystem"

time    v.device_name             v.mount_point
----    ----                      ----
....    D:",v.mount_point="D:\    D:
```

**Comment by repeatedly** [comment]
> I guess that it is caused by influxdb-ruby, but I think that asking here is a good start.

Yes. fluent-plugin-influxdb doesn't touch event content.

**Comment by CheyiLin** [comment]
The bug has been fixed in https://rubygems.org/gems/influxdb/versions/0.4.2

It would be great that we upgrade the influxdb-ruby to >= 0.4, but will lose Ruby < 2.2 compatibility.

Any ideas?

**Comment by dmke** [comment]
If Ruby 1.9+ compatibility is absolute necessary, I could be persuaded to backport this bugfix into another 0.3.x release. However, Ruby 2.1 is [EOL since 2017/04](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/), so I need some strong arguments (or a PR against the [influxdb-ruby/stable-03 tree](https://github.com/influxdata/influxdb-ruby/tree/stable-03) 😉)

**Comment by repeatedly** [comment]
I think Ruby 1.9/2.0 support is no longer needed.
But ruby 2.1 is still widely used including td-agent 2 so backport above fix to 0.3 release is very helpful for me.
If 0.4 release is compatible with 0.3, we can relax version constraint of this plugin.
If not, we need changes to support 0.3 and 0.4 together.

**Comment by dmke** [comment]
> But ruby 2.1 is still widely used

Is it? My impression is that the 2.0→2.1→2.2→2.3 migration process is really painless and people didn't stay long on the previous version. Are there distribution apart from Debian Jessie, which still ship Ruby 2.1?

> If 0.4 release is compatible with 0.3,

Mostly. 0.4 removed Ruby compat for MRI < 2.2, which allowed some major code cleanups. Since then only a few new features have landed in the gem: I consider it feature complete, but sometimes people find new use cases :-).

The API hasn't changed between 0.3 and 0.4 in a backward compatible manner (if it has, it is a bug), so depending on `~> 0.3` should suffice. v0.4 has set [`required_ruby_version`](https://github.com/influxdata/influxdb-ruby/blob/master/influxdb.gemspec#L21) in its `.gemspec`. I don't know whether `fluent-gem install ...` knows how to interpret that setting, though...

I think, cobbling together a bugfix release for 0.3 should be too hard (tomorrow, anyway).

**Comment by repeatedly** [comment]
> The API hasn't changed between 0.3 and 0.4 in a backward compatible manner (if it has, it is a bug), 

Okay. I will check it.

> I don't know whether fluent-gem install ... knows how to interpret that setting, though...

To avoid this problem, we need to install v0.3 seriese first like this: https://github.com/fangli/fluent-plugin-influxdb#installation

**Comment by dmke** [comment]
Sorry, it was late for me yesterday:

> The API hasn't changed between 0.3 and 0.4 in a backward compatible manner

should read

> The API hasn't changed between 0.3 and 0.4 in a *backward **in**compatible* manner

**Comment by dmke** [comment]
I have just released v0.3.17 of the InfluxDB gem, backporting the bugfixes applied to the v0.4 tree.

---

> we need to install v0.3 seriese first like this: [...]

I believe, I've miscommunicated my intent: When I said "so depending on `~> 0.3` should suffice", I was referring to your [`.gemspec`](https://github.com/fangli/fluent-plugin-influxdb/blob/master/fluent-plugin-influxdb.gemspec#L20). If `fluent-gem install fluent-plugin-influxdb -v 1.0.0.rc2` does the right thing, it will pick up InfluxDB v0.3 on MRI <= 2.1 and v0.4 on MRI > 2.1.

**Comment by repeatedly** [comment]
> I have just released v0.3.17 of the InfluxDB gem, backporting the bugfixes applied to the v0.4 tree

Thanks for great work!

> it will pick up InfluxDB v0.3 on MRI <= 2.1 and v0.4 on MRI > 2.1.

No because gemspec doesn't have such metadata in one gemspec file. `fluent-gem install fluent-plugin-influxdb -v 1.0.0.rc2` will try to install latest influxdb gem and it causes same error on MRI <= 2.1.

**Comment by CheyiLin** [comment]
@dmke Thanks for the 0.3 backport! Just repack the docker image and everything works expected!
@repeatedly I think it's ok to close the issue since we don't have to change anything. 😄

Again, thanks for your great work!

Confirmed that the query result from influxdb HTTP API is correct now.
```json
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "system.filesystem",
                    "columns": [
                        "time",
                        "v.device_name",
                        "v.mount_point"
                    ],
                    "values": [
                        [
                            1501729298688,
                            "D:\\",
                            "D:\\"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by dmke** [comment]
> `fluend-gem install ...` will try to install latest influxdb gem and it causes same error on MRI <= 2.1

Well, in that case, you should stay on 0.3.x. Except for some more cleanup and refactoring, I don't have anything special planned for the 0.x series. For the time being, 0.3 and 0.4 should stay mostly compatible, with some minor new interfaces in 0.4.

However, when influxdata/influxdb#8477 lands, major refactoring in the client code will, which likely necessitate a 1.0 release of the InfluxDB gem (and, at this point, will drop MRI 2.1 support for good).

> Confirmed that the query result from influxdb HTTP API is correct now.

:+1: Yay! :tada:
