### ISSUE TITLE
accept integer for float field

### ISSUE THREAD

**Issue by ash0080** [fangli/fluent-plugin-influxdb#92]
Now, insert an integer to a float field will throw an "already exists as type float" error

because there isn't precision float in Javascript, e.x:  1.0, 2.0... 10.0 all will be converted to integer automatically. 
And as described in the [3032](https://github.com/influxdata/influxdb/issues/3032), now all numbers in influxdb are float, so could this be fixed?
Or could add an auto parse func from String?

**Comment by repeatedly** [comment]
How about using record_transformer filter to convert number type?

```
<filter test.**>
  @type record_transformer
  enable_ruby true
  <record>
    foo ${record["foo"].to_f}
  </record>
</filter>
```

**Comment by ash0080** [comment]
Sure, that's what I did.  but It's better to run without other tricky operations. at least fitting the influxdb‘s protocol. so why not transform all number to float？

**Comment by Coac** [comment]
I am having the same issue as @ash0080 
The record transformer solution is nice when you have one field with that problem, but when you have dozens, and when you want to add later another key, you need to edit the fluent conf...
It's a good idea to make it float by default

**Comment by Coac** [comment]
I added a PR for that https://github.com/fangli/fluent-plugin-influxdb/pull/95

**Comment by Coac** [comment]
I closed the issue since it is fixed, the PR got merged :+1:
